const products = [
  {
    id: "T1001",
    name: "Basic Crew Neck T-Shirt",
    type: "T-Shirt",
    category: "Men's Clothing",
    price: 19.99,
    color: ["Black"],
    size: ["S", "M", "L", "XL"],
    dressStyle: "Casual",
    material: "Cotton",
    brand: "UrbanWear",
    rating: 4.5,
    reviewCount: 500,
    stockStatus: "In Stock",
    arrivalTime: "2024-11-01",
    isNewArrival: true,
    image: "https://png.pngtree.com/png-vector/20240401/ourmid/pngtree-black-t-shirt-mockup-transparent-background-png-image_12256281.png",
    tags: ["basic", "everyday", "comfortable"],
    features: [
      "Soft fabric",
      "Machine washable",
      "Classic fit"
    ]
  },
  {
    id: "T1002",
    name: "Graphic Print T-Shirt",
    type: "T-Shirt",
    category: "Women's Clothing",
    price: 24.99,
    color: ["Red"],
    size: ["M", "L", "XL"],
    dressStyle: "Trendy",
    material: "Polyester",
    brand: "StylePrints",
    rating: 4.2,
    reviewCount: 320,
    stockStatus: "In Stock",
    arrivalTime: "2024-10-28",
    isNewArrival: false,
    image: "https://png.pngtree.com/png-vector/20240123/ourmid/pngtree-red-t-shirt-png-image_11479816.png",
    tags: ["graphic", "colorful", "trendy"],
    features: [
      "Vibrant print",
      "Lightweight fabric",
      "Breathable"
    ]
  },
  {
    id: "T1003",
    name: "Athletic Fit T-Shirt",
    type: "T-Shirt",
    category: "Men's Activewear",
    price: 29.99,
    color: ["Blue"],
    size: ["S", "M", "L", "XL", "XXL"],
    dressStyle: "Sportswear",
    material: "Polyester Blend",
    brand: "ActiveLife",
    rating: 4.7,
    reviewCount: 250,
    stockStatus: "In Stock",
    arrivalTime: "2024-11-02",
    isNewArrival: true,
    image: "https://img.freepik.com/free-psd/t-shirt-with-blue-color-isolated-transparent-background_191095-23065.jpg",
    tags: ["athletic", "sports", "moisture-wicking"],
    features: [
      "Quick-dry fabric",
      "Flexible stretch",
      "Breathable"
    ]
  },
  {
    id: "T1004",
    name: "V-Neck Casual T-Shirt",
    type: "T-Shirt",
    category: "Women's Clothing",
    price: 22.49,
    color: ["Pink"],
    size: ["XS", "S", "M", "L"],
    dressStyle: "Casual",
    material: "Cotton",
    brand: "ChicStyle",
    rating: 4.3,
    reviewCount: 270,
    stockStatus: "Limited Stock",
    arrivalTime: "2024-10-25",
    isNewArrival: false,
    image: "https://banner2.cleanpng.com/20180618/viv/kisspng-t-shirt-neckline-gildan-activewear-clothing-hot-pink-5b2813d36b1276.1874976115293531714386.jpg",
    tags: ["v-neck", "soft", "comfortable"],
    features: [
      "Soft fabric",
      "V-neck cut",
      "Relaxed fit"
    ]
  },
  {
    id: "T1005",
    name: "Raglan Baseball T-Shirt",
    type: "T-Shirt",
    category: "Unisex Clothing",
    price: 27.99,
    color: ["White"],
    size: ["S", "M", "L", "XL", "XXL"],
    dressStyle: "Casual",
    material: "Cotton Blend",
    brand: "AllSeasons",
    rating: 4.6,
    reviewCount: 190,
    stockStatus: "In Stock",
    arrivalTime: "2024-11-04",
    isNewArrival: true,
    image: "https://img.freepik.com/premium-psd/raglan-sleeve-t-shirt-transparent-background_1085577-67806.jpg",
    tags: ["raglan", "baseball", "casual"],
    features: [
      "Contrast sleeves",
      "Soft and durable",
      "Machine washable"
    ]
  },
  {
    id: "T1006",
    name: "Henley Long Sleeve T-Shirt",
    type: "T-Shirt",
    category: "Men's Clothing",
    price: 34.99,
    color: ["Brown"],
    size: ["M", "L", "XL", "XXL"],
    dressStyle: "Casual",
    material: "Cotton",
    brand: "RusticWear",
    rating: 4.4,
    reviewCount: 350,
    stockStatus: "In Stock",
    arrivalTime: "2024-10-30",
    isNewArrival: false,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3IgbFhcBLtj-XrEAnavOK1g63wHvbeICCIg&s",
    tags: ["henley", "long sleeve", "rustic"],
    features: [
      "Button neckline",
      "Comfort fit",
      "Warm for cooler weather"
    ]
  },
  {
    id: "T1007",
    name: "Oversized Tie-Dye T-Shirt",
    type: "T-Shirt",
    category: "Women's Clothing",
    price: 26.49,
    color: ["Purple"],
    size: ["S", "M", "L"],
    dressStyle: "Streetwear",
    material: "Cotton Blend",
    brand: "StreetFusion",
    rating: 4.1,
    reviewCount: 130,
    stockStatus: "Limited Stock",
    arrivalTime: "2024-10-29",
    isNewArrival: true,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOEqVLXFZvb41eKWMdkena6X7H-EVpPMwyqQ&s",
    tags: ["tie-dye", "oversized", "trendy"],
    features: [
      "Loose fit",
      "Unique tie-dye pattern",
      "Comfortable for everyday wear"
    ]
  },
  {
    id: "T1008",
    name: "Pocket Tee",
    type: "T-Shirt",
    category: "Men's Clothing",
    price: 18.99,
    color: ["black"],
    size: ["S", "M", "L", "XL"],
    dressStyle: "Casual",
    material: "Cotton",
    brand: "ComfortLine",
    rating: 4.0,
    reviewCount: 230,
    stockStatus: "In Stock",
    arrivalTime: "2024-10-31",
    isNewArrival: false,
    image: "https://banner2.cleanpng.com/20180330/tje/kisspng-t-shirt-amazon-com-sleeve-pocket-tshirt-5abe700c103189.8838275415224299640663.jpg",
    tags: ["pocket tee", "classic", "comfortable"],
    features: [
      "Chest pocket",
      "Soft fabric",
      "Standard fit"
    ]
  },
  {
    id: "T1009",
    name: "Slim Fit Polo T-Shirt",
    type: "T-Shirt",
    category: "Men's Clothing",
    price: 39.99,
    color: ["White"],
    size: ["M", "L", "XL", "XXL"],
    dressStyle: "Smart Casual",
    material: "Pique Cotton",
    brand: "Elegance",
    rating: 4.8,
    reviewCount: 410,
    stockStatus: "In Stock",
    arrivalTime: "2024-11-03",
    isNewArrival: true,
    image: "https://i.pinimg.com/originals/29/0d/44/290d444ddfe28476d54d2f55b3d659a0.png",
    tags: ["polo", "slim fit", "smart"],
    features: [
      "Collared neckline",
      "Breathable material",
      "Slim fit design"
    ]
  },
  {
    id: "S1001",
    name: "Classic Denim Shorts",
    type: "Shorts",
    category: "Women's Clothing",
    price: 29.99,
    color: ["Blue"],
    size: ["S", "M", "L", "XL"],
    dressStyle: "Casual",
    material: "Denim",
    brand: "UrbanDenim",
    rating: 4.5,
    reviewCount: 280,
    stockStatus: "In Stock",
    arrivalTime: "2024-10-25",
    isNewArrival: false,
    image: "https://png.pngtree.com/element_our/20190528/ourmid/pngtree-classic-fashion-wild-denim-shorts-image_1124359.jpg",
    tags: ["denim", "classic", "comfortable"],
    features: [
      "High-waisted",
      "Distressed finish",
      "Machine washable"
    ]
  },
  {
    id: "S1002",
    name: "Athletic Gym Shorts",
    type: "Shorts",
    category: "Men's Activewear",
    price: 24.99,
    color: ["Gray"],
    size: ["S", "M", "L", "XL", "XXL"],
    dressStyle: "Sportswear",
    material: "Polyester",
    brand: "ActiveLife",
    rating: 4.8,
    reviewCount: 420,
    stockStatus: "In Stock",
    arrivalTime: "2024-11-01",
    isNewArrival: true,
    image: "https://as3athletics.com/cdn/shop/products/mockup-df3964a2_1024x.png?v=1597721858",
    tags: ["gym", "workout", "breathable"],
    features: [
      "Moisture-wicking",
      "Quick-dry fabric",
      "Elastic waistband"
    ]
  },
  {
    id: "S1003",
    name: "Casual Chino Shorts",
    type: "Shorts",
    category: "Men's Clothing",
    price: 34.99,
    color: ["Red"],
    size: ["M", "L", "XL", "XXL"],
    dressStyle: "Smart Casual",
    material: "Cotton",
    brand: "ChinoClassics",
    rating: 4.4,
    reviewCount: 310,
    stockStatus: "Limited Stock",
    arrivalTime: "2024-10-29",
    isNewArrival: false,
    image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.cleanpng.com%2Fpng-bermuda-shorts-school-uniform-clothing-sportswear-1142420%2F&psig=AOvVaw3H3Vg9N1INJ1XqFbMioHj6&ust=1730619413050000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCOi2wu2RvYkDFQAAAAAdAAAAABAJ",
    tags: ["chino", "smart", "casual"],
    features: [
      "Four pockets",
      "Button and zipper closure",
      "Lightweight"
    ]
  },
  {
    id: "S1004",
    name: "Linen Beach Shorts",
    type: "Shorts",
    category: "Unisex Clothing",
    price: 39.99,
    color: ["White"],
    size: ["S", "M", "L"],
    dressStyle: "Beachwear",
    material: "Linen",
    brand: "BreezyLinen",
    rating: 4.6,
    reviewCount: 180,
    stockStatus: "In Stock",
    arrivalTime: "2024-11-02",
    isNewArrival: true,
    image: "https://img.freepik.com/premium-psd/swim-shorts-mockup-transparent-background_933496-83322.jpg",
    tags: ["beach", "relaxed", "lightweight"],
    features: [
      "Drawstring waist",
      "Breathable fabric",
      "Comfortable fit"
    ]
  },
  {
    id: "S1005",
    name: "Running Shorts with Pockets",
    type: "Shorts",
    category: "Women's Activewear",
    price: 27.99,
    color: ["Blue"],
    size: ["XS", "S", "M", "L"],
    dressStyle: "Sportswear",
    material: "Nylon Blend",
    brand: "RunFlex",
    rating: 4.7,
    reviewCount: 150,
    stockStatus: "In Stock",
    arrivalTime: "2024-11-03",
    isNewArrival: true,
    image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.freepik.com%2Fpremium-psd%2Fblue-shorts-isolated-transparent-background_181416465.htm&psig=AOvVaw07UpN85JVWevq6aCDJZzTF&ust=1730619487371000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCOC5v5OSvYkDFQAAAAAdAAAAABAZ",
    tags: ["running", "pockets", "athletic"],
    features: [
      "Hidden pockets",
      "Stretchable fabric",
      "Quick-drying"
    ]
  },
  {
    id: "S1006",
    name: "Cargo Utility Shorts",
    type: "Shorts",
    category: "Men's Clothing",
    price: 32.49,
    color: ["Brown"],
    size: ["M", "L", "XL", "XXL"],
    dressStyle: "Outdoor",
    material: "Cotton",
    brand: "OutdoorGear",
    rating: 4.3,
    reviewCount: 390,
    stockStatus: "Limited Stock",
    arrivalTime: "2024-10-30",
    isNewArrival: false,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5nHb7EUcNeNZaxeYb87ha8lYJiJdzduYhQQ&s",
    tags: ["cargo", "utility", "outdoor"],
    features: [
      "Multiple pockets",
      "Durable material",
      "Adjustable waistband"
    ]
  },
  {
    id: "S1007",
    name: "High-Waisted Biker Shorts",
    type: "Shorts",
    category: "Women's Activewear",
    price: 22.49,
    color: ["Black"],
    size: ["S", "M", "L"],
    dressStyle: "Athleisure",
    material: "Spandex Blend",
    brand: "FlexyFit",
    rating: 4.9,
    reviewCount: 500,
    stockStatus: "In Stock",
    arrivalTime: "2024-10-28",
    isNewArrival: false,
    image: "https://assets.sugarfreeshops.com/media/catalog/product/cache/7a4b6ad88a313560ec271e2411344d4e/2/2/22860020_110_5.png",
    tags: ["biker", "high-waisted", "stretch"],
    features: [
      "Body-hugging fit",
      "Flexible stretch",
      "Breathable fabric"
    ]
  },
  {
    id: "S1008",
    name: "Relaxed Fit Sweat Shorts",
    type: "Shorts",
    category: "Unisex Clothing",
    price: 25.99,
    color: ["Gray"],
    size: ["S", "M", "L", "XL"],
    dressStyle: "Loungewear",
    material: "Cotton Blend",
    brand: "CozyLounge",
    rating: 4.2,
    reviewCount: 200,
    stockStatus: "In Stock",
    arrivalTime: "2024-10-26",
    isNewArrival: false,
    image: "https://png.pngtree.com/png-vector/20241016/ourlarge/pngtree-cotton-shorts-grey-png-image_14089586.png",
    tags: ["sweat", "relaxed", "comfortable"],
    features: [
      "Elastic waistband",
      "Soft fleece fabric",
      "Relaxed fit"
    ]
  },
  {
    id: "S1009",
    name: "Comfort shorts",
    type: "Shorts",
    category: "Women's Clothing",
    price: 31.99,
    color: ["Blue"],
    size: ["S", "M", "L", "XL"],
    dressStyle: "Casual",
    material: "Denim",
    brand: "TrendyCuts",
    rating: 4.0,
    reviewCount: 320,
    stockStatus: "In Stock",
    arrivalTime: "2024-11-04",
    isNewArrival: true,
    image: "https://img.freepik.com/premium-psd/blue-shorts-isolated-transparent-background_220739-26975.jpg",
    tags: ["cutoffs", "high-waisted", "trendy"],
    features: [
      "Raw hem",
      "Distressed look",
      "Comfortable fit"
    ]
  },
  {
    id: "H1001",
    name: "Classic Pullover Hoodie",
    type: "Hoodie",
    category: "Men's Clothing",
    price: 49.99,
    color: ["Black"],
    size: ["S", "M", "L", "XL"],
    dressStyle: "Casual",
    material: "Cotton Blend",
    brand: "UrbanBasics",
    rating: 4.7,
    reviewCount: 320,
    stockStatus: "In Stock",
    arrivalTime: "2024-11-05",
    isNewArrival: true,
    image: "https://img.freepik.com/free-psd/black-hooded-sweatshirt-isolated-transparent-background-clothing-apparel-fashion-garment-p_125540-6358.jpg",
    tags: ["pullover", "casual", "comfortable"],
    features: [
      "Kangaroo pocket",
      "Ribbed cuffs and hem",
      "Drawstring hood"
    ]
  },
  {
    id: "H1002",
    name: "Lightweight Zip-Up Hoodie",
    type: "Hoodie",
    category: "Women's Clothing",
    price: 39.99,
    color: ["Pink"],
    size: ["XS", "S", "M", "L"],
    dressStyle: "Casual",
    material: "Polyester",
    brand: "EverydayWear",
    rating: 4.5,
    reviewCount: 290,
    stockStatus: "Limited Stock",
    arrivalTime: "2024-10-25",
    isNewArrival: false,
    image: "https://media.istockphoto.com/id/1319572167/photo/mens-hooded-jacket-with-zipper-for-your-design-mockup-for-print.jpg?s=612x612&w=0&k=20&c=wMO5ChqYcMHUDIBpybamI10PRvk39vW9AgBj6CY3fRI=",
    tags: ["zip-up", "lightweight", "soft"],
    features: [
      "Full zipper",
      "Lightweight fabric",
      "Side pockets"
    ]
  },
  {
    id: "H1003",
    name: "Oversized Hoodie",
    type: "Hoodie",
    category: "Unisex Clothing",
    price: 54.99,
    color: ["Green"],
    size: ["M", "L", "XL", "XXL"],
    dressStyle: "Streetwear",
    material: "Cotton Blend",
    brand: "StreetSmart",
    rating: 4.8,
    reviewCount: 500,
    stockStatus: "In Stock",
    arrivalTime: "2024-11-01",
    image: "https://img.freepik.com/premium-psd/green-hoodie-isolated-transparent-background-png_1073071-1164.jpg",
    isNewArrival: true,
    tags: ["oversized", "trendy", "comfortable"],
    features: [
      "Baggy fit",
      "Extra-large hood",
      "Ribbed cuffs"
    ]
  },
  {
    id: "H1004",
    name: "Performance Athletic Hoodie",
    type: "Hoodie",
    category: "Men's Activewear",
    price: 59.99,
    color: ["Blue"],
    size: ["S", "M", "L", "XL"],
    dressStyle: "Sportswear",
    material: "Polyester Blend",
    brand: "AthleteGear",
    rating: 4.6,
    reviewCount: 410,
    stockStatus: "In Stock",
    arrivalTime: "2024-10-28",
    isNewArrival: false,
    image: "https://img.freepik.com/premium-photo/blue-hoodie-mockup-sweatshirt-with-pocket-insulated-white-background_124507-29139.jpg?w=360",
    tags: ["athletic", "performance", "quick-dry"],
    features: [
      "Moisture-wicking fabric",
      "Breathable",
      "Reflective accents"
    ]
  },
  {
    id: "H1005",
    name: "Sherpa Lined Hoodie",
    type: "Hoodie",
    category: "Women's Clothing",
    price: 64.99,
    color: ["Gray"],
    size: ["S", "M", "L", "XL"],
    dressStyle: "Winterwear",
    material: "Fleece",
    brand: "WarmEssentials",
    rating: 4.9,
    reviewCount: 340,
    stockStatus: "Limited Stock",
    arrivalTime: "2024-11-03",
    isNewArrival: true,
    image: " https://images-cdn.ubuy.co.in/6586b6ae9a9ab76bc3314f60-men-s-heavyweight-thermal-zip-up-hoodie.jpg",
    tags: ["sherpa", "lined", "warm"],
    features: [
      "Sherpa lining",
      "Extra warmth",
      "Zipper closure"
    ]
  },
  {
    id: "H1006",
    name: "Crop Hoodie",
    type: "Hoodie",
    category: "Women's Clothing",
    price: 34.99,
    color: ["Black"],
    size: ["XS", "S", "M", "L"],
    dressStyle: "Streetwear",
    material: "Cotton",
    brand: "ChicWear",
    rating: 4.3,
    reviewCount: 200,
    stockStatus: "In Stock",
    arrivalTime: "2024-10-29",
    isNewArrival: false,
    image: "https://happydude.in/wp-content/uploads/2020/12/Plain-Black-Crop-Hoodie.jpeg",
    tags: ["crop", "fashion", "streetwear"],
    features: [
      "Cropped fit",
      "Raw hem",
      "Drawstring hood"
    ]
  },
  {
    id: "H1007",
    name: "Tech Fleece Hoodie",
    type: "Hoodie",
    category: "Unisex Activewear",
    price: 79.99,
    color: ["White"],
    size: ["M", "L", "XL", "XXL"],
    dressStyle: "Sportswear",
    material: "Tech Fleece",
    brand: "ProFlex",
    rating: 4.7,
    reviewCount: 450,
    stockStatus: "In Stock",
    arrivalTime: "2024-10-30",
    isNewArrival: false,
    image: "https://shoprepforces.com/cdn/shop/products/Untitleddesign_78.png?v=1687896998",
    tags: ["tech fleece", "warm", "lightweight"],
    features: [
      "Thermal insulation",
      "Zippered pockets",
      "Lightweight warmth"
    ]
  },
  {
    id: "H1008",
    name: "Vintage Washed Hoodie",
    type: "Hoodie",
    category: "Men's Clothing",
    price: 42.99,
    color: ["Red"],
    size: ["S", "M", "L", "XL"],
    dressStyle: "Casual",
    material: "Cotton",
    brand: "RetroVibe",
    rating: 4.2,
    reviewCount: 260,
    stockStatus: "In Stock",
    arrivalTime: "2024-11-04",
    isNewArrival: true,
    image: "https://img.freepik.com/premium-psd/red-hoodie-isolated-transparent-background_220739-12874.jpg",
    tags: ["vintage", "washed", "soft"],
    features: [
      "Vintage wash",
      "Kangaroo pocket",
      "Soft interior"
    ]
  },
  {
    id: "H1009",
    name: "Eco-Friendly Hoodie",
    type: "Hoodie",
    category: "Unisex Clothing",
    price: 44.99,
    color: ["Green"],
    size: ["XS", "S", "M", "L", "XL"],
    dressStyle: "Eco-Friendly",
    material: "Recycled Cotton",
    brand: "GreenEarth",
    rating: 4.5,
    reviewCount: 180,
    stockStatus: "In Stock",
    arrivalTime: "2024-10-27",
    isNewArrival: true,
    image: "https://img.freepik.com/premium-psd/green-hoodie-isolated-transparent-background-png_1073071-1171.jpg",
    tags: ["eco-friendly", "sustainable", "recycled"],
    features: [
      "Made from recycled materials",
      "Soft touch",
      "Low-impact dye"
    ]
  },
  {
    id: "S1001",
    name: "Classic Oxford Shirt",
    type: "Shirt",
    category: "Men's Clothing",
    price: 34.99,
    color: ["White"],
    size: ["S", "M", "L", "XL"],
    dressStyle: "Formal",
    material: "Cotton",
    brand: "UrbanClassics",
    rating: 4.7,
    reviewCount: 220,
    stockStatus: "In Stock",
    arrivalTime: "2024-11-02",
    isNewArrival: true,
    image: "https://png.pngtree.com/png-vector/20240718/ourlarge/pngtree-white-shirt-classic-dress-formal-png-image_13141487.png",
    tags: ["oxford", "formal", "classic"],
    features: [
      "Button-down collar",
      "Chest pocket",
      "Breathable fabric"
    ]
  },
  {
    id: "S1002",
    name: "Casual Plaid Shirt",
    type: "Shirt",
    category: "Men's Clothing",
    price: 29.99,
    color: ["Red"],
    size: ["S", "M", "L", "XL"],
    dressStyle: "Casual",
    material: "Flannel",
    brand: "LumberJack",
    rating: 4.6,
    reviewCount: 340,
    stockStatus: "Limited Stock",
    arrivalTime: "2024-10-30",
    isNewArrival: false,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9proom-LFPG0uY4KhyEcYrK5klu_9cIlJTA&s",
    tags: ["plaid", "casual", "flannel"],
    features: [
      "Soft fabric",
      "Button cuffs",
      "Relaxed fit"
    ]
  },
  {
    id: "S1003",
    name: "Slim Fit Dress Shirt",
    type: "Shirt",
    category: "Men's Clothing",
    price: 44.99,
    color: ["Black"],
    size: ["S", "M", "L", "XL", "XXL"],
    dressStyle: "Formal",
    material: "Cotton Blend",
    brand: "ExecutiveStyle",
    rating: 4.8,
    reviewCount: 450,
    stockStatus: "In Stock",
    arrivalTime: "2024-11-04",
    isNewArrival: true,
    image: "https://static.vecteezy.com/system/resources/thumbnails/048/396/505/small_2x/mockup-of-a-black-long-sleeve-dress-shirt-isolated-on-transparent-background-free-png.png",
    tags: ["slim fit", "formal", "elegant"],
    features: [
      "Slim fit design",
      "Non-iron fabric",
      "Adjustable cuffs"
    ]
  },
  {
    id: "S1004",
    name: "Printed Hawaiian Shirt",
    type: "Shirt",
    category: "Men's Clothing",
    price: 24.99,
    color: ["Yellow"],
    size: ["M", "L", "XL"],
    dressStyle: "Casual",
    material: "Polyester",
    brand: "IslandVibes",
    rating: 4.4,
    reviewCount: 300,
    stockStatus: "In Stock",
    arrivalTime: "2024-11-01",
    isNewArrival: false,
    image: "https://i.pinimg.com/originals/87/00/46/8700460df214430825af7699da58196a.jpg",
    tags: ["hawaiian", "tropical", "printed"],
    features: [
      "Tropical print",
      "Lightweight fabric",
      "Short sleeves"
    ]
  },
  {
    id: "S1005",
    name: "Chambray Button-Up Shirt",
    type: "Shirt",
    category: "Women's Clothing",
    price: 32.99,
    color: ["Blue"],
    size: ["XS", "S", "M", "L"],
    dressStyle: "Casual",
    material: "Chambray",
    brand: "EverydayWear",
    rating: 4.5,
    reviewCount: 280,
    stockStatus: "In Stock",
    arrivalTime: "2024-10-28",
    isNewArrival: true,
    image: "https://img.freepik.com/premium-psd/hang-blue-linen-casual-shirt-isolated-transparent-background_220739-46939.jpg",
    tags: ["chambray", "lightweight", "button-up"],
    features: [
      "Soft chambray fabric",
      "Chest pocket",
      "Curved hem"
    ]
  },
  {
    id: "S1006",
    name: "Relaxed Linen Shirt",
    type: "Shirt",
    category: "Women's Clothing",
    price: 39.99,
    color: ["White"],
    size: ["S", "M", "L", "XL"],
    dressStyle: "Casual",
    material: "Linen",
    brand: "NatureWear",
    rating: 4.7,
    reviewCount: 320,
    stockStatus: "In Stock",
    arrivalTime: "2024-10-29",
    isNewArrival: false,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDDhCSd4AvFpicgntKrK4n_HIlt2bGvAeMPA&s",
    tags: ["linen", "relaxed fit", "breathable"],
    features: [
      "Breathable linen",
      "Roll-up sleeves",
      "Relaxed fit"
    ]
  },
  {
    id: "S1007",
    name: "Denim Western Shirt",
    type: "Shirt",
    category: "Men's Clothing",
    price: 42.99,
    color: ["Brown"],
    size: ["S", "M", "L", "XL"],
    dressStyle: "Casual",
    material: "Denim",
    brand: "WesternEdge",
    rating: 4.5,
    reviewCount: 280,
    stockStatus: "In Stock",
    arrivalTime: "2024-11-03",
    isNewArrival: true,
    image: "https://schaeferoutfitter.com/cdn/shop/files/2152_western-denim-snap-shirt_khaki_front.jpg?v=1719445991&width=1080",
    tags: ["denim", "western", "casual"],
    features: [
      "Snap buttons",
      "Pointed yoke",
      "Chest pockets"
    ]
  },
  {
    id: "S1008",
    name: "Eco-Friendly Organic Shirt",
    type: "Shirt",
    category: "Unisex Clothing",
    price: 45.99,
    color: ["Gray"],
    size: ["XS", "S", "M", "L", "XL"],
    dressStyle: "Eco-Friendly",
    material: "Organic Cotton",
    brand: "EcoFashion",
    rating: 4.6,
    reviewCount: 310,
    stockStatus: "In Stock",
    arrivalTime: "2024-10-26",
    isNewArrival: true,
    image: "https://img.freepik.com/premium-psd/folded-gray-shirt-isolated-transparent-background-png-psd_888962-1850.jpg",
    tags: ["organic", "eco-friendly", "sustainable"],
    features: [
      "Organic cotton",
      "Environmentally friendly dyes",
      "Soft touch"
    ]
  },
  {
    id: "S1009",
    name: "Retro Bowling Shirt",
    type: "Shirt",
    category: "Men's Clothing",
    price: 28.99,
    color: ["Yellow"],
    size: ["S", "M", "L", "XL"],
    dressStyle: "Vintage",
    material: "Polyester Blend",
    brand: "RetroStyle",
    rating: 4.4,
    reviewCount: 230,
    stockStatus: "In Stock",
    arrivalTime: "2024-10-31",
    isNewArrival: false,
    image: "https://i.pinimg.com/474x/5e/7d/1c/5e7d1ce7f9908ba078e252c8e7232582.jpg",
    tags: ["retro", "bowling", "vintage"],
    features: [
      "Retro color blocking",
      "Button-up front",
      "Lightweight fabric"
    ]
  },
  {
    id: "J1001",
    name: "Classic Straight Jeans",
    type: "Jeans",
    category: "Men's Clothing",
    price: 49.99,
    color: ["Blue"],
    size: ["30", "32", "34", "36", "38"],
    dressStyle: "Casual",
    material: "Denim",
    brand: "DenimEssentials",
    rating: 4.6,
    reviewCount: 450,
    stockStatus: "In Stock",
    arrivalTime: "2024-10-29",
    isNewArrival: true,
    image: "https://img.freepik.com/free-psd/blue-jeans-isolated-transparent-background_191095-17292.jpg",
    tags: ["classic", "straight fit", "casual"],
    features: [
      "Straight fit",
      "Five-pocket style",
      "Durable denim"
    ]
  },
  {
    id: "J1002",
    name: "Skinny Fit Jeans",
    type: "Jeans",
    category: "Women's Clothing",
    price: 54.99,
    color: ["Gray"],
    size: ["24", "26", "28", "30", "32"],
    dressStyle: "Trendy",
    material: "Stretch Denim",
    brand: "FashionLine",
    rating: 4.7,
    reviewCount: 380,
    stockStatus: "Limited Stock",
    arrivalTime: "2024-10-25",
    isNewArrival: false,
    image: "https://banner2.cleanpng.com/20180630/tpl/kisspng-jeans-slim-fit-pants-fashion-denim-ripped-denim-5b37d4aedf0673.8464891115303855829135.jpg",
    tags: ["skinny fit", "stretchable", "trendy"],
    features: [
      "Skinny fit",
      "Stretch fabric",
      "High-rise waist"
    ]
  },
  {
    id: "J1003",
    name: "Relaxed Fit Jeans",
    type: "Jeans",
    category: "Men's Clothing",
    price: 39.99,
    color: ["Blue"],
    size: ["30", "32", "34", "36", "38", "40"],
    dressStyle: "Casual",
    material: "Denim",
    brand: "ComfortWear",
    rating: 4.5,
    reviewCount: 200,
    stockStatus: "In Stock",
    arrivalTime: "2024-10-26",
    isNewArrival: false,
    image: "https://img.freepik.com/free-psd/blue-jeans-isolated-transparent-background_191095-17296.jpg",
    tags: ["relaxed fit", "comfortable", "classic"],
    features: [
      "Relaxed fit",
      "Roomy through thigh",
      "Durable stitching"
    ]
  },
  {
    id: "J1004",
    name: "Bootcut Jeans",
    type: "Jeans",
    category: "Women's Clothing",
    price: 47.99,
    color: ["black"],
    size: ["26", "28", "30", "32", "34"],
    dressStyle: "Casual",
    material: "Cotton Denim",
    brand: "BootTrend",
    rating: 4.4,
    reviewCount: 250,
    stockStatus: "In Stock",
    arrivalTime: "2024-11-01",
    isNewArrival: true,
    image: "https://png.pngtree.com/png-clipart/20231021/original/pngtree-jeans-isolated-on-white-background-pattern-picture-image_13189141.png",
    tags: ["bootcut", "casual", "stretch denim"],
    features: [
      "Bootcut style",
      "Comfort stretch",
      "Mid-rise"
    ]
  },
  {
    id: "J1005",
    name: "High-Waisted Mom Jeans",
    type: "Jeans",
    category: "Women's Clothing",
    price: 44.99,
    color: ["Red"],
    size: ["24", "26", "28", "30", "32"],
    dressStyle: "Vintage",
    material: "Rigid Denim",
    brand: "RetroDenim",
    rating: 4.6,
    reviewCount: 320,
    stockStatus: "In Stock",
    arrivalTime: "2024-10-31",
    isNewArrival: false,
    image: "https://i.etsystatic.com/17536761/r/il/b393a6/6014511255/il_fullxfull.6014511255_8l12.jpg",
    tags: ["high-waisted", "vintage", "mom jeans"],
    features: [
      "High-rise",
      "Tapered leg",
      "Non-stretch denim"
    ]
  },
  {
    id: "J1006",
    name: "Distressed Ripped Jeans",
    type: "Jeans",
    category: "Men's Clothing",
    price: 59.99,
    color: ["Blue"],
    size: ["30", "32", "34", "36"],
    dressStyle: "Trendy",
    material: "Stretch Denim",
    brand: "StreetStyle",
    rating: 4.3,
    reviewCount: 280,
    stockStatus: "Limited Stock",
    arrivalTime: "2024-11-02",
    isNewArrival: true,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSf_EcCWhT6dp2Gkvieu3UNYAcOTHdNDNICEQ&s",
    tags: ["distressed", "ripped", "trendy"],
    features: [
      "Distressed details",
      "Stretch fabric",
      "Slim fit"
    ]
  },
  {
    id: "J1007",
    name: "Straight Leg Cargo Jeans",
    type: "Jeans",
    category: "Unisex Clothing",
    price: 42.99,
    color: ["Brown"],
    size: ["S", "M", "L", "XL"],
    dressStyle: "Casual",
    material: "Cotton Denim",
    brand: "UtilityWear",
    rating: 4.5,
    reviewCount: 240,
    stockStatus: "In Stock",
    arrivalTime: "2024-10-30",
    isNewArrival: false,
    image: "https://www.victoriabeckham.com/cdn/shop/files/UntitledSession20033_1500x.jpg?v=1724946579",
    tags: ["cargo", "utility", "comfortable"],
    features: [
      "Multiple pockets",
      "Straight leg",
      "Durable fabric"
    ]
  },
  {
    id: "J1008",
    name: "Flared Jeans",
    type: "Jeans",
    category: "Women's Clothing",
    price: 52.99,
    color: ["Black"],
    size: ["24", "26", "28", "30", "32"],
    dressStyle: "Retro",
    material: "Denim",
    brand: "FashionRetro",
    rating: 4.7,
    reviewCount: 260,
    stockStatus: "In Stock",
    arrivalTime: "2024-10-28",
    isNewArrival: true,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqMr2JYrSu37Kchl7y2Svjg1W6D3rFgeY-Xg&s",
    tags: ["flared", "retro", "high-rise"],
    features: [
      "High-rise waist",
      "Flared bottom",
      "Stretch fabric"
    ]
  },
  {
    id: "J1009",
    name: "Slim Fit Black Jeans",
    type: "Jeans",
    category: "Men's Clothing",
    price: 49.99,
    color: ["Black"],
    size: ["30", "32", "34", "36", "38"],
    dressStyle: "Casual",
    material: "Denim",
    brand: "DenimEssentials",
    rating: 4.8,
    reviewCount: 430,
    stockStatus: "In Stock",
    arrivalTime: "2024-11-04",
    isNewArrival: true,
    image: "https://png.pngtree.com/element_our/20190528/ourmid/pngtree-creative-fashion-beautiful-elegant-pants-image_1125002.jpg",
    tags: ["slim fit", "black", "classic"],
    features: [
      "Slim fit",
      "Stretch denim",
      "Five-pocket style"
    ]
  }
];

export default products